#!/bin/bash
# ============================================
# GitHub Stats Auto-Updater
# ============================================
# Run via cron: 0 4 * * * /root/job_bot/scripts/update_github.sh
#
# This script:
# 1. Reads application stats
# 2. Updates README.md with live badges
# 3. Copies latest PDFs to showcase folder
# 4. Commits and pushes to GitHub

set -e

REPO_DIR="/root/job_bot"
OUTPUT_DIR="$REPO_DIR/output"
SHOWCASE_DIR="$REPO_DIR/showcase"
STATS_FILE="$OUTPUT_DIR/.counter.json"

cd "$REPO_DIR"

# ============================================
# Read Stats
# ============================================

if [ -f "$STATS_FILE" ]; then
    TOTAL=$(jq '.total' "$STATS_FILE")
    REMOTE=$(jq '.remote' "$STATS_FILE")
    LOCAL=$(jq '.local' "$STATS_FILE")
else
    TOTAL=0
    REMOTE=0
    LOCAL=0
fi

# Calculate percentages
if [ "$TOTAL" -gt 0 ]; then
    REMOTE_PCT=$(echo "scale=1; $REMOTE * 100 / $TOTAL" | bc)
    LOCAL_PCT=$(echo "scale=1; $LOCAL * 100 / $TOTAL" | bc)
else
    REMOTE_PCT="0.0"
    LOCAL_PCT="0.0"
fi

# Get timestamp
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S PST')

# ============================================
# Generate README.md
# ============================================

cat > README.md << EOF
# 🤖 Autonomous Job Application Agent

> An AI-powered system that searches for jobs, tailors resumes, and generates applications while I sleep.

![Total Applications](https://img.shields.io/badge/Applications-${TOTAL}-blue?style=for-the-badge)
![Remote](https://img.shields.io/badge/Remote-${REMOTE_PCT}%25-green?style=for-the-badge)
![Local](https://img.shields.io/badge/Local-${LOCAL_PCT}%25-orange?style=for-the-badge)

## 📊 Live Statistics

| Metric | Count |
|--------|-------|
| **Total Applications** | ${TOTAL} |
| **Remote Positions** | ${REMOTE} (${REMOTE_PCT}%) |
| **Local Positions** | ${LOCAL} (${LOCAL_PCT}%) |

### Target Distribution
- 🏠 **75% Local** (Long Beach / LA area)
- 🌐 **25% Remote**

## 🎯 Current Focus
- **Role:** IT Support / Help Desk / System Administrator
- **Location:** Long Beach, CA (open to remote)
- **Studying:** AWS Cloud Practitioner

## 🛠️ Tech Stack

| Component | Technology |
|-----------|------------|
| **Orchestration** | n8n (self-hosted) |
| **AI Brain** | DeepSeek V3 API |
| **PDF Generation** | Gotenberg |
| **Job Scraping** | python-jobspy |
| **Hosting** | Hetzner Cloud VPS |

## 📁 Project Structure

\`\`\`
job-agent/
├── infrastructure/
│   ├── docker-compose.yml    # VPS deployment
│   └── n8n-workflow.json     # Importable workflow
├── agent/
│   ├── job_agent.py          # Browser automation agent
│   └── simple_hunter.py      # Lightweight scraper
├── prompts/
│   ├── resume_system.txt     # Resume generation prompt
│   └── cover_letter.txt      # Cover letter prompt
├── showcase/
│   ├── sample_resume.pdf     # Latest generated resume
│   └── sample_cover.pdf      # Latest generated cover letter
└── scripts/
    └── update_github.sh      # This auto-update script
\`\`\`

## 🔄 How It Works

\`\`\`
┌─────────────────────────────────────────────────────────────┐
│                    AUTONOMOUS LOOP                          │
│                                                             │
│  1. 🔍 Search Indeed/LinkedIn for IT jobs                  │
│  2. 📋 Filter by 75/25 local/remote ratio                  │
│  3. 📤 Send job description to n8n webhook                 │
│  4. 🧠 DeepSeek tailors resume + cover letter              │
│  5. 🖨️  Gotenberg generates PDFs                           │
│  6. 💾 Save to output folder with tracking                 │
│  7. 📊 Update stats and GitHub                             │
│  8. 🔁 Repeat                                              │
└─────────────────────────────────────────────────────────────┘
\`\`\`

## 💡 The Meta-Play

Every cover letter includes:

> *"Full transparency: This application was generated by an autonomous job agent I built. You are employer #${TOTAL}. I would welcome the chance to demonstrate both my IT skills and my automation capabilities."*

This turns the job search itself into a portfolio piece.

## 📈 Why This Works

1. **Scalability** - Process 100+ jobs/day for pennies
2. **Consistency** - Every resume is keyword-optimized
3. **Proof of Skill** - The system IS the portfolio
4. **Differentiation** - Nobody else is doing this

---

*Last updated: ${TIMESTAMP}*
*Auto-generated by the Job Application Agent*
EOF

# ============================================
# Copy Latest PDFs to Showcase
# ============================================

mkdir -p "$SHOWCASE_DIR"

# Get most recent resume and cover letter
LATEST_RESUME=$(ls -t "$OUTPUT_DIR"/*_Resume.pdf 2>/dev/null | head -1)
LATEST_COVER=$(ls -t "$OUTPUT_DIR"/*_CoverLetter.pdf 2>/dev/null | head -1)

if [ -n "$LATEST_RESUME" ]; then
    cp "$LATEST_RESUME" "$SHOWCASE_DIR/sample_resume.pdf"
fi

if [ -n "$LATEST_COVER" ]; then
    cp "$LATEST_COVER" "$SHOWCASE_DIR/sample_cover.pdf"
fi

# ============================================
# Generate STATS.md
# ============================================

cat > STATS.md << EOF
# 📊 Application Statistics

*Auto-generated: ${TIMESTAMP}*

## Summary

- **Total Applications:** ${TOTAL}
- **Remote:** ${REMOTE} (${REMOTE_PCT}%)
- **Local:** ${LOCAL} (${LOCAL_PCT}%)

## Target vs Actual

| Type | Target | Actual |
|------|--------|--------|
| Local | 75% | ${LOCAL_PCT}% |
| Remote | 25% | ${REMOTE_PCT}% |

## Timeline

See \`output/applications.csv\` for full application history.
EOF

# ============================================
# Git Commit & Push
# ============================================

git add -A
git commit -m "📊 Auto-update: ${TOTAL} applications (${TIMESTAMP})" || echo "Nothing to commit"
git push origin main || echo "Push failed - check credentials"

echo "✅ GitHub updated successfully"
